In [1]:
# pip install cmake

In [2]:
# pip install "C:\Users\USER\Downloads\dlib-19.24.1-cp311-cp311-win_amd64.whl"

In [3]:
# pip install face_recognition

In [4]:
# pip install opencv-python

In [5]:
import cv2
import numpy
import os 
import face_recognition

In [6]:
path='images'

In [7]:
mylist=os.listdir(path)
mylist

['kalpana.jpg',
 'mbappe.jpg',
 'messi.jpg',
 'ronaldo.jpg',
 'sania.jpg',
 'sunita.jpg']

In [8]:
imgs=[]
classnames=[]
for img in mylist:
    imgpath=os.path.join(path,img)
    current_img=cv2.imread(imgpath)
    print(current_img)
    imgs.append(current_img)
    classnames.append(img.split('.')[0])
print(len(imgs))
print(classnames)

[[[ 82 107  97]
  [ 82 107  97]
  [ 82 107  97]
  ...
  [ 77 101  91]
  [ 78 102  92]
  [ 78 102  92]]

 [[ 82 107  97]
  [ 82 107  97]
  [ 81 106  96]
  ...
  [ 77 101  91]
  [ 78 102  92]
  [ 78 102  92]]

 [[ 82 107  97]
  [ 82 107  97]
  [ 81 106  96]
  ...
  [ 77 101  91]
  [ 78 102  92]
  [ 78 102  92]]

 ...

 [[ 73  97  87]
  [ 73  97  87]
  [ 74  98  88]
  ...
  [ 78 103  93]
  [ 78 103  93]
  [ 78 103  93]]

 [[ 71  95  85]
  [ 71  95  85]
  [ 71  95  85]
  ...
  [ 78 103  93]
  [ 78 103  93]
  [ 78 103  93]]

 [[ 69  93  83]
  [ 69  93  83]
  [ 70  94  84]
  ...
  [ 78 103  93]
  [ 78 103  93]
  [ 78 103  93]]]
[[[ 55  73  80]
  [ 54  72  79]
  [ 53  71  78]
  ...
  [ 48  60  64]
  [ 48  60  64]
  [ 48  60  64]]

 [[ 55  73  80]
  [ 54  72  79]
  [ 53  71  78]
  ...
  [ 47  59  63]
  [ 47  59  63]
  [ 47  59  63]]

 [[ 55  73  80]
  [ 55  73  80]
  [ 54  72  79]
  ...
  [ 47  59  63]
  [ 47  59  63]
  [ 47  59  63]]

 ...

 [[232 227 226]
  [243 238 235]
  [254 247 244]
  ..

In [9]:
def faceencoding(images):
    encodelist=[]
    for img in images:
        img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        face_in_frame=face_recognition.face_locations(img)
        #print(face_in_frame)
        encode=face_recognition.face_encodings(img,face_in_frame)[0]
        #print(encode)
        encodelist.append(encode)
    return encodelist
encode_list_known_faces=faceencoding(imgs)
print(encode_list_known_faces)


[array([-0.09354728,  0.09292261,  0.02389267, -0.04335576, -0.11268189,
       -0.05329613, -0.011157  , -0.01423684,  0.18862632, -0.11556327,
        0.1965296 , -0.06061085, -0.22441611,  0.01224343,  0.05202728,
        0.12133154, -0.09997172, -0.18694314, -0.0501456 , -0.05573179,
        0.04046518, -0.04739422, -0.00880755,  0.11191387, -0.1951751 ,
       -0.32754439, -0.08967441, -0.09814475, -0.09711121, -0.08300845,
       -0.04131058,  0.06054428, -0.19953498, -0.07318449,  0.01599691,
        0.03952464,  0.00902093, -0.00871265,  0.17732991,  0.01124448,
       -0.20983186,  0.03604006,  0.08922931,  0.23888665,  0.15889302,
        0.03952467,  0.00915325, -0.00845092,  0.09899418, -0.28069744,
        0.01176625,  0.12893355,  0.14299135, -0.0075197 ,  0.0627633 ,
       -0.11920818,  0.00288252,  0.10678625, -0.2211898 ,  0.05296986,
        0.01847992, -0.07753555, -0.09515862, -0.04424033,  0.24130045,
        0.21995863, -0.0937659 , -0.08848473,  0.17070183, -0.1

In [10]:
import numpy as np

In [11]:
video=cv2.VideoCapture(0)
while True:
    suc,img=video.read()
    img1=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    face_in_frame=face_recognition.face_locations(img1)
    #print(face_in_frame)
    encoded_face=face_recognition.face_encodings(img1,face_in_frame)
    #print(encoded_face)
    for enc_face,faceloc in zip(encoded_face,face_in_frame):
        matches=face_recognition.compare_faces(encode_list_known_faces,enc_face)
        #print(matches)
        face_dist=face_recognition.face_distance(encode_list_known_faces,enc_face)
        #print(face_dist)
        matchind=np.argmin(face_dist)
        #print(matchind)
        if matches[matchind]==True:
            name=classnames[matchind]
            print(name)
            y1,x2,y2,x1=faceloc
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,255),4)
            cv2.putText(img,name,(x1,y1),cv2.FONT_HERSHEY_COMPLEX,fontScale=4,color=(255,0,234),thickness=10)
    cv2.imshow('IMAGE',img)
    if cv2.waitKey(1) & 0XFF==ord('q'):
        break
video.release()
cv2.destroyAllWindows()
    

kalpana
kalpana
sunita
sunita
sunita
sunita
sunita
sunita
sunita
sunita
sunita
sunita
sunita
sunita
sunita
sunita
sunita
sunita
