In [1]:
# pip install cmake

In [2]:
# pip install "C:\Users\USER\Downloads\dlib-19.24.1-cp311-cp311-win_amd64.whl"

In [3]:
# pip install face_recognition

In [4]:
# pip install opencv-python

In [5]:
import cv2
import numpy
import os 
import face_recognition

In [6]:
path='images'

In [7]:
mylist=os.listdir(path)
mylist

['alia.jpg',
 'anaswara.jpeg',
 'genelia.jpg',
 'keerthi.jpg',
 'mamitha.jpg',
 'surya.jpg']

In [8]:
imgs=[]
classnames=[]
for img in mylist:
    imgpath=os.path.join(path,img)
    current_img=cv2.imread(imgpath)
    print(current_img)
    imgs.append(current_img)
    classnames.append(img.split('.')[0])
print(len(imgs))
print(classnames)

[[[121 119 111]
  [121 119 111]
  [121 119 111]
  ...
  [141 138 133]
  [141 138 133]
  [141 138 133]]

 [[122 120 112]
  [122 120 112]
  [122 120 112]
  ...
  [141 138 133]
  [141 138 133]
  [141 138 133]]

 [[122 120 112]
  [122 120 112]
  [122 120 112]
  ...
  [141 138 133]
  [141 138 133]
  [141 138 133]]

 ...

 [[134 130 129]
  [134 130 129]
  [134 130 129]
  ...
  [152 148 147]
  [152 148 147]
  [152 148 147]]

 [[134 130 129]
  [134 130 129]
  [134 130 129]
  ...
  [152 148 147]
  [152 148 147]
  [152 148 147]]

 [[134 130 129]
  [134 130 129]
  [134 130 129]
  ...
  [152 148 147]
  [152 148 147]
  [152 148 147]]]
[[[161 157 163]
  [162 158 164]
  [162 158 164]
  ...
  [153 156 171]
  [152 155 170]
  [152 154 172]]

 [[161 157 163]
  [162 158 164]
  [162 158 164]
  ...
  [153 156 171]
  [153 156 171]
  [152 154 172]]

 [[159 157 163]
  [160 158 164]
  [160 158 164]
  ...
  [154 157 172]
  [153 156 171]
  [153 155 173]]

 ...

 [[111 115 143]
  [111 115 143]
  [111 115 143]
  ..

In [9]:
def faceencoding(images):
    encodelist=[]
    for img in images:
        img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        face_in_frame=face_recognition.face_locations(img)
        #print(face_in_frame)
        encode=face_recognition.face_encodings(img,face_in_frame)[0]
        #print(encode)
        encodelist.append(encode)
    return encodelist
encode_list_known_faces=faceencoding(imgs)
print(encode_list_known_faces)


[array([-0.1649766 ,  0.05218622,  0.06443257, -0.08570033, -0.10392535,
        0.0031332 , -0.03576193, -0.05268649,  0.10794201, -0.1463858 ,
        0.16002503, -0.06784165, -0.16161948,  0.05097909, -0.06920056,
        0.1413334 , -0.14686808, -0.18044874, -0.07707767, -0.07703936,
       -0.00070053,  0.04293503, -0.09291176,  0.12302905, -0.14895232,
       -0.3809357 , -0.05047705, -0.0861752 , -0.05631927, -0.03092977,
       -0.02754038,  0.10487127, -0.23525256, -0.02128669,  0.06655081,
        0.20206717,  0.07136337,  0.01334345,  0.13587025,  0.02051294,
       -0.25894496,  0.05850298,  0.20806563,  0.33779135,  0.20330213,
       -0.00486241, -0.00078282,  0.00426839,  0.16568582, -0.25273508,
        0.02583871,  0.12964593,  0.17226443,  0.01690277,  0.09315385,
       -0.10952465, -0.00752476,  0.09138588, -0.15745822,  0.05339833,
        0.05587545, -0.06517143,  0.02052122, -0.0916722 ,  0.21405645,
        0.06856391, -0.11970745, -0.13994527,  0.19550945, -0.2

In [14]:
import numpy as np

In [19]:
video=cv2.VideoCapture(0)
while True:
    suc,img=video.read()
    img1=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    face_in_frame=face_recognition.face_locations(img1)
    #print(face_in_frame)
    encoded_face=face_recognition.face_encodings(img1,face_in_frame)
    #print(encoded_face)
    for enc_face,faceloc in zip(encoded_face,face_in_frame):
        matches=face_recognition.compare_faces(encode_list_known_faces,enc_face)
        #print(matches)
        face_dist=face_recognition.face_distance(encode_list_known_faces,enc_face)
        #print(face_dist)
        matchind=np.argmin(face_dist)
        #print(matchind)
        if matches[matchind]==True:
            name=classnames[matchind]
            print(name)
            y1,x2,y2,x1=faceloc
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,255),4)
            cv2.putText(img,name,(x1,y1),cv2.FONT_HERSHEY_COMPLEX,fontScale=4,color=(255,0,234),thickness=10)
    cv2.imshow('IMAGE',img)
    if cv2.waitKey(1) & 0XFF==ord('q'):
        break
video.release()
cv2.destroyAllWindows()
    

anaswara
anaswara
anaswara
anaswara
anaswara
anaswara
anaswara
anaswara
anaswara
anaswara
anaswara
anaswara
anaswara
anaswara
anaswara
anaswara
anaswara
anaswara
anaswara
anaswara
anaswara
anaswara
anaswara
